apiVersion: v2
name: jk-test
description: A Helm chart using image docker.io/jgkirschbaum/jk-test for testing
type: application
version: 1.0.0
appVersion: 1.0.3
icon: "https://img.shields.io/badge/Chart-jk--test-informational?style=flat-square"
home: "https://github.com/jgkirschbaum/jk-test"
sources:
  - "https://github.com/jgkirschbaum/jk-test/chart/jk-test"
