---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jktest
  labels:
    app: jktest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jktest
  template:
    metadata:
      labels:
        app: jktest
        owner: kirscju
    spec:
      serviceAccountName: jktest
      terminationGracePeriodSeconds: 1
      podSecurityContext:
        fsGroup: 2000
      containers:
        - name: jktest
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
          image: jgkirschbaum/jk-test:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
